### ISSUE TITLE
`spawn npm ENOENT` when running gen-roles

### ISSUE THREAD

**Issue by AleskiWeb** [puresec/serverless-puresec-cli#17]
I am getting the error `spawn npm ENOENT` when I run the `serverless puresec gen-roles" command.

```
 Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           10.15.3
     Serverless Version:     1.42.2
```

**Comment by piotr-kania-arria** [comment]
I found the same issue

`
Serverless: Load command puresec
Serverless: Load command puresec:gen-roles
Serverless: Invoke puresec:gen-roles

  Error --------------------------------------------------

  spawn npm ENOENT

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
From previous event:
    at PluginManager.invoke (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\lib\classes\PluginManager.js:446:22)
    at PluginManager.run (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\lib\classes\PluginManager.js:477:17)
    at variables.populateService.then (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\lib\Serverless.js:112:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\lib\Serverless.js:99:6)
    at serverless.init.then (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\bin\serverless:43:28)
    at C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\bin\serverless:43:6)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\bin\serverless:28:46
    at Object.<anonymous> (C:\Users\piotr.kania\AppData\Roaming\nvm\v8.12.0\node_modules\serverless\bin\serverless:65:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     win32
     Node Version:           8.12.0
     Serverless Version:     1.45.1

`

**Comment by ErikAndreas** [comment]
Same here:
` Error: spawn npm ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
      at onErrorNT (internal/child_process.js:467:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              13.7.0
     Framework Version:         1.63.0
     Plugin Version:            3.3.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0`

**Comment by ErikAndreas** [comment]
Seems this entire repo has been rather quiet since Puresec got acquired(?) by Palo Alto Networks?

**Comment by iangriffin** [comment]
Same issue here 

> Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.1
     Framework Version:         1.67.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3

**Comment by funkel1989** [comment]
Has anyone figured this out yet?
